# 该镜像基于最新的CentOS7官方镜像进行构建
FROM centos:7
MAINTAINER kid20191028 lisl@servyou.com.cn
# 设置工作目录
WORKDIR /
# 安装 epel-release 包
RUN yum install -y epel-release
# 安装基础的工具链
RUN yum install -y net-tools vim wget lrzsz tree screen lsof tcpdump nmap telnet dos2unix unix2dos bash-completion OpenIPMI-tools sysstat iptraf ntp zlib-devel ncurses-devel openssl openssh-serve openssl-devel mysql-devel mysql supervisor git redis gcc gcc-c++ golang htop iperf iftop iproute less unzip zip tcpdump nmap yum-util nfs-utils iotop java-1.8.0-openjdk && yum clean all
#RUN yum install -y net-tools vim wget lrzsz tree screen lsof tcpdump nmap telnet dos2unix unix2dos bash-completion OpenIPMI-tools sysstat iptraf ntp zlib-devel ncurses-devel openssl openssh-serve openssl-devel mysql-devel mysql supervisor git redis gcc gcc-c++ golang htop iperf iftop less unzip zip tcpdump nmap yum-util nfs-utils iotop java-1.8.0-openjdk  &>/dev/null && yum clean all
# 安装ZK工具
ENV ZK_DIR=apache-zookeeper-3.5.6-bin
COPY $ZK_DIR/ /zookeeper/$ZK_DIR
# 安装部署kafka工具
ENV KFK_DIR=kafka_2.12-2.3.1
COPY $KFK_DIR/ /kafka/$KFK_DIR
#设置环境变量
ENV PATH=$PATH:/zookeeper/$ZK_DIR/bin:/kafaka/$KFK_DIR/bin \
    LANG=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8
# 拷贝启动脚本
COPY docker-entrypoint.sh /
COPY check_pod_health.sh  /
# 启动镜像默认运行挂起脚本
#CMD [ "/docker-entrypoint.sh" ]
#CMD [ "sleep","2" ]
#CMD [ "/check_pod_health.sh" ]
ENTRYPOINT [ "/bin/bash", "-c","/docker-entrypoint.sh &", "/bin/bash", "-c", " /check_pod_health.sh &" ]
